# Generated by Django 5.2.6 on 2025-10-09 03:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlacklistedToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.TextField(
                        help_text="The blacklisted JWT token", unique=True
                    ),
                ),
                (
                    "blacklisted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When the token was blacklisted",
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(help_text="When the token would have expired"),
                ),
            ],
            options={
                "verbose_name": "Blacklisted Token",
                "verbose_name_plural": "Blacklisted Tokens",
                "indexes": [
                    models.Index(
                        fields=["expires_at"], name="authenticat_expires_aff8d0_idx"
                    )
                ],
            },
        ),
    ]
