# Generated by Django 3.0.7 on 2021-11-05 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Occupier', '0002_auto_20211105_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupier',
            name='dob',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
