version: "3.9"

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8000"
    depends_on:
      - db

    environment:
      - DJANGO_SETTINGS_MODULE=config.django.production
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DB_ENGINE=django.db.backends.postgresql
      - DB_HOST=db

volumes:
  postgres_data:
