version: "3.9"

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-occupy7}
      POSTGRES_USER: ${DATABASE_USER:-sam}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-chiraqmony}
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "80:8000"
    depends_on:
      - db
    environment:
      - DJANGO_DEBUG=True
      - SECRET_KEY=django-insecure-dev-secret-key-change-this-in-production-12345abcdef
      - ALLOWED_HOSTS=localhost,127.0.0.1,occupy-app.com,[::1]
      - DJANGO_SETTINGS_MODULE=config.django.development
      - DB_ENGINE=django.db.backends.postgresql
      - DB_HOST=db

    command: python manage.py runserver 0.0.0.0:8000

volumes:
  postgres_data:
