version: "3.9"

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ${DATABASE_NAME:-occupy7}
      POSTGRES_USER: ${DATABASE_USER:-sam}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-chiraqmony}
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./:/app
    ports:
      - "80:8000"
    depends_on:
      - db
    environment:
      - DEBUG=${DJANGO_DEBUG:-1}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost 127.0.0.1 [::1]}
      - DATABASE_URL=postgres://${DATABASE_USER:-sam}:${DATABASE_PASSWORD:-chiraqmony}@db:5432/${DATABASE_NAME:-occupy7}
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  postgres_data:
