# Generated by Django 3.0.7 on 2021-11-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Occupier', '0004_auto_20211105_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupier',
            name='dob',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
    ]
