# Generated by Django 3.0.7 on 2021-11-17 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Occupier', '0007_occupier_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupier',
            name='dob',
            field=models.DateField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
