# Generated by Django 3.0.7 on 2021-11-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Occupier', '0009_auto_20211117_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupier',
            name='dob',
            field=models.DateField(blank=True, max_length=60, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='occupier',
            name='password',
            field=models.CharField(max_length=60),
        ),
    ]
