# Generated by Django 3.0.7 on 2021-11-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Occupier', '0010_auto_20211117_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupier',
            name='dob',
            field=models.DateField(blank=True, null=True, unique=True),
        ),
    ]
