# Generated by Django 3.0.7 on 2021-11-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Occupier', '0011_auto_20211117_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupier',
            name='password',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
