# Generated by Django 3.0.7 on 2021-11-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Occupier', '0016_auto_20211120_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupier',
            name='password',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
