# Generated by Django 3.0.7 on 2021-12-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Occupier', '0018_auto_20211130_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupier',
            name='first_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='occupier',
            name='last_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
