# Generated by Django 3.2.4 on 2022-04-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Occupier', '0019_auto_20211202_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupier',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
