# Generated by Django 4.2.7 on 2023-11-10 07:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Occupier', '0024_auto_20230829_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupier',
            name='blocked_occupier',
            field=models.ManyToManyField(blank=True, related_name='occupier_blocked', to=settings.AUTH_USER_MODEL),
        ),
    ]
