# Generated by Django 5.0.6 on 2024-11-27 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Occupier', '0028_businesspage_delete_businessprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessPage',
        ),
    ]
