# Generated by Django 5.2.6 on 2025-10-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Occupier", "0029_delete_businesspage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occupier",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
