# Generated by Django 3.0.7 on 2021-11-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Occupier', '0015_auto_20211120_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupier',
            name='password',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
