"""Add feedback table

Revision ID: 1013e47f3abb
Revises: dc06b73b7b71
Create Date: 2025-11-05 05:51:39.425151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1013e47f3abb'
down_revision: Union[str, Sequence[str], None] = 'dc06b73b7b71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('feedback_type', sa.Enum('BETA_APPLICATION', 'GENERAL_FEEDBACK', 'BUG_REPORT', 'FEATURE_REQUEST', 'OTHER', name='feedback_type'), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feedback'))
    )
    op.drop_index(op.f('uq_users_username_ci'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('uq_users_username_ci'), 'users', [sa.literal_column('lower(username::text)')], unique=True)
    op.drop_table('feedback')
    # ### end Alembic commands ###
