"""0001

Revision ID: 97fd6734af55
Revises: 
Create Date: 2025-10-21 12:50:47.422467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97fd6734af55'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('occupations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_occupations')),
    sa.UniqueConstraint('name', name=op.f('uq_occupations_name')),
    sa.UniqueConstraint('slug', name=op.f('uq_occupations_slug'))
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_image_url', sa.String(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_private_account', sa.Boolean(), nullable=False),
    sa.Column('is_business_page', sa.Boolean(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('chats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_user_id', sa.UUID(), nullable=False),
    sa.Column('client_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_user_id'], ['users.id'], name=op.f('fk_chats_business_user_id_users')),
    sa.ForeignKeyConstraint(['client_user_id'], ['users.id'], name=op.f('fk_chats_client_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chats'))
    )
    op.create_table('cliques',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('privacy', sa.Enum('PUBLIC', 'PRIVATE', name='privacy'), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('cancellation_cutoff_hours', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_cliques_owner_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cliques'))
    )
    op.create_table('follows',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('follower_user_id', sa.UUID(), nullable=False),
    sa.Column('followee_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'BLOCKED', name='follow_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('follower_user_id <> followee_user_id', name=op.f('ck_follows_ck_follows_no_self_follow')),
    sa.ForeignKeyConstraint(['followee_user_id'], ['users.id'], name=op.f('fk_follows_followee_user_id_users')),
    sa.ForeignKeyConstraint(['follower_user_id'], ['users.id'], name=op.f('fk_follows_follower_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_follows')),
    sa.UniqueConstraint('follower_user_id', 'followee_user_id', name='uq_follows_pair')
    )
    op.create_index('ix_follows_followee_user_id', 'follows', ['followee_user_id'], unique=False)
    op.create_index('ix_follows_follower_user_id', 'follows', ['follower_user_id'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('mime', sa.String(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], name=op.f('fk_media_owner_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('LIKE', 'COMMENT', 'FOLLOW', 'BOOKING_REQUEST', 'BOOKING_CONFIRMED', 'BOOKING_CANCELLED', 'REVIEW', 'SYSTEM', 'MESSAGE', name='notification_type'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_user_id_is_read', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_table('user_occupations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('occupation_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['occupation_id'], ['occupations.id'], name=op.f('fk_user_occupations_occupation_id_occupations')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_occupations_user_id_users')),
    sa.PrimaryKeyConstraint('user_id', 'occupation_id', name=op.f('pk_user_occupations'))
    )
    op.create_table('availabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clique_id', sa.UUID(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_until', sa.Date(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(is_recurring = true AND date IS NULL AND day_of_week IS NOT NULL) OR (is_recurring = false AND date IS NOT NULL AND day_of_week IS NULL)', name=op.f('ck_availabilities_ck_availabilities_recurring_constraints')),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name=op.f('ck_availabilities_ck_availabilities_day_of_week_range')),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_availabilities_ck_availabilities_end_after_start')),
    sa.ForeignKeyConstraint(['clique_id'], ['cliques.id'], name=op.f('fk_availabilities_clique_id_cliques')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_availabilities'))
    )
    op.create_table('clique_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clique_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clique_id'], ['cliques.id'], name=op.f('fk_clique_invites_clique_id_cliques')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clique_invites')),
    sa.UniqueConstraint('token', name=op.f('uq_clique_invites_token'))
    )
    op.create_table('clique_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clique_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MEMBER', name='role'), nullable=False),
    sa.Column('status', sa.Enum('JOINED', 'PENDING', 'BANNED', name='membership_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clique_id'], ['cliques.id'], name=op.f('fk_clique_members_clique_id_cliques')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_clique_members_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_clique_members')),
    sa.UniqueConstraint('clique_id', 'user_id', name='uq_clique_members_unique')
    )
    op.create_table('clique_occupations',
    sa.Column('clique_id', sa.UUID(), nullable=False),
    sa.Column('occupation_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['clique_id'], ['cliques.id'], name=op.f('fk_clique_occupations_clique_id_cliques')),
    sa.ForeignKeyConstraint(['occupation_id'], ['occupations.id'], name=op.f('fk_clique_occupations_occupation_id_occupations')),
    sa.PrimaryKeyConstraint('clique_id', 'occupation_id', name=op.f('pk_clique_occupations'))
    )
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('sender_user_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('media_id', sa.UUID(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('fk_messages_chat_id_chats'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_messages_media_id_media')),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], name=op.f('fk_messages_sender_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index('ix_messages_chat_id_sent_at', 'messages', ['chat_id', 'sent_at'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clique_id', sa.UUID(), nullable=False),
    sa.Column('author_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'POSTED', 'ARCHIVED', name='post_status'), nullable=False),
    sa.Column('content_format', sa.Enum('MARKDOWN', name='content_format'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], name=op.f('fk_posts_author_user_id_users')),
    sa.ForeignKeyConstraint(['clique_id'], ['cliques.id'], name=op.f('fk_posts_clique_id_cliques')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts'))
    )
    op.create_index('ix_posts_clique_id_created_at', 'posts', ['clique_id', 'created_at'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clique_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_minor', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('buffer_minutes', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clique_id'], ['cliques.id'], name=op.f('fk_services_clique_id_cliques')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services'))
    )
    op.create_index('ix_services_clique_id_is_active', 'services', ['clique_id', 'is_active'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clique_id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('start_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='booking_status'), nullable=False),
    sa.Column('cancelled_by', sa.Enum('OWNER', 'CLIENT', name='cancelled_by'), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_ts > start_ts', name=op.f('ck_bookings_ck_bookings_end_after_start')),
    sa.ForeignKeyConstraint(['clique_id'], ['cliques.id'], name=op.f('fk_bookings_clique_id_cliques')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_bookings_service_id_services')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bookings_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bookings')),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_bookings_user_idempotency')
    )
    op.create_index('ix_bookings_clique_id_start_ts', 'bookings', ['clique_id', 'start_ts'], unique=False)
    op.create_index('ix_bookings_service_id_start_ts', 'bookings', ['service_id', 'start_ts'], unique=False)
    op.create_index('ix_bookings_user_id_start_ts', 'bookings', ['user_id', 'start_ts'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('parent_comment_id', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], name=op.f('fk_comments_parent_comment_id_comments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_comments_post_id_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_comments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    op.create_index('ix_comments_post_id_created_at', 'comments', ['post_id', 'created_at'], unique=False)
    op.create_table('post_likes',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_likes_post_id_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_post_likes_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id', name=op.f('pk_post_likes'))
    )
    op.create_index('ix_post_likes_user_id', 'post_likes', ['user_id'], unique=False)
    op.create_table('post_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name=op.f('fk_post_media_media_id_media'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_media_post_id_posts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_post_media')),
    sa.UniqueConstraint('post_id', 'position', name='uq_post_media_post_id_position')
    )
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('rater_user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name=op.f('ck_reviews_ck_reviews_rating_range')),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('fk_reviews_booking_id_bookings')),
    sa.ForeignKeyConstraint(['rater_user_id'], ['users.id'], name=op.f('fk_reviews_rater_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reviews')),
    sa.UniqueConstraint('booking_id', name=op.f('uq_reviews_booking_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('post_media')
    op.drop_index('ix_post_likes_user_id', table_name='post_likes')
    op.drop_table('post_likes')
    op.drop_index('ix_comments_post_id_created_at', table_name='comments')
    op.drop_table('comments')
    op.drop_index('ix_bookings_user_id_start_ts', table_name='bookings')
    op.drop_index('ix_bookings_service_id_start_ts', table_name='bookings')
    op.drop_index('ix_bookings_clique_id_start_ts', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('ix_services_clique_id_is_active', table_name='services')
    op.drop_table('services')
    op.drop_index('ix_posts_clique_id_created_at', table_name='posts')
    op.drop_table('posts')
    op.drop_index('ix_messages_chat_id_sent_at', table_name='messages')
    op.drop_table('messages')
    op.drop_table('clique_occupations')
    op.drop_table('clique_members')
    op.drop_table('clique_invites')
    op.drop_table('availabilities')
    op.drop_table('user_occupations')
    op.drop_index('ix_notifications_user_id_is_read', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('media')
    op.drop_index('ix_follows_follower_user_id', table_name='follows')
    op.drop_index('ix_follows_followee_user_id', table_name='follows')
    op.drop_table('follows')
    op.drop_table('cliques')
    op.drop_table('chats')
    op.drop_table('users')
    op.drop_table('occupations')
    # ### end Alembic commands ###
