# Generated by Django 5.0.6 on 2025-08-31 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Occupy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='occupier',
            new_name='user',
        ),
    ]
