# Generated by Django 3.0.7 on 2021-11-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Occupier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupier',
            name='dob',
            field=models.DateField(blank=True, max_length=8, null=True),
        ),
    ]
