# Generated by Django 3.0.7 on 2021-11-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Occupier', '0008_auto_20211117_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupier',
            name='password',
            field=models.CharField(max_length=25),
        ),
    ]
