# Generated by Django 3.0.7 on 2021-11-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Occupier', '0013_auto_20211117_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupier',
            name='password',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
