# Generated by Django 3.0.7 on 2021-11-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Occupier', '0014_auto_20211120_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupier',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
