# Generated by Django 3.2.13 on 2022-08-10 12:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('occupation', models.CharField(default='', max_length=90)),
                ('level', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='public', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=400)),
                ('caption', models.CharField(max_length=400)),
                ('posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('posted', 'Posted')], default='posted', max_length=12)),
                ('clique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliques', to='Occupy.clique')),
                ('occupier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clique_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-posted',),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
                ('occupier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_authored', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='Occupy.post')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='CliquePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_set', to='Occupy.clique')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliques_set', to='Occupy.post')),
            ],
            options={
                'unique_together': {('clique', 'post')},
            },
        ),
    ]
