# Generated by Django 3.2.13 on 2022-08-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Occupy', '0002_post_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='post',
            name='posted',
        ),
        migrations.AlterField(
            model_name='post',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
