# Generated by Django 5.0.6 on 2025-08-31 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Occupy', '0002_rename_occupier_review_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='date',
            new_name='created_at',
        ),
    ]
