# Generated by Django 3.2.13 on 2022-08-13 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Occupy', '0003_auto_20220810_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
