# Generated by Django 3.2.13 on 2022-08-14 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Occupy', '0004_post_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='clique',
            name='occupiers',
            field=models.ManyToManyField(blank=True, related_name='cliques', to=settings.AUTH_USER_MODEL),
        ),
    ]
