# Generated by Django 5.2.6 on 2025-10-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Occupy", "0004_availability_service_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clique",
            name="level",
            field=models.CharField(
                choices=[("PUBLIC", "Public"), ("PRIVATE", "Private")],
                default="PUBLIC",
                help_text="\n        Public: Any user can join a public clique\n        Private: Requires an invite to join clique\n        ",
                max_length=15,
            ),
        ),
    ]
