# Generated by Django 3.2.13 on 2022-08-14 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Occupy', '0005_clique_occupiers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clique',
            old_name='occupiers',
            new_name='members',
        ),
    ]
