# Generated by Django 3.2.13 on 2022-08-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Occupy', '0006_rename_occupiers_clique_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clique',
            old_name='members',
            new_name='occupiers',
        ),
    ]
