# Generated by Django 3.2 on 2023-06-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Occupy', '0009_clique_occupiers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='clique',
            name='occupation',
        ),
    ]
