# Generated by Django 3.2.13 on 2023-06-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Occupy', '0011_clique_occupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clique',
            name='occupiers',
        ),
        migrations.AlterField(
            model_name='clique',
            name='occupation',
            field=models.CharField(default='', max_length=200),
        ),
    ]
