# Generated by Django 3.2.13 on 2023-06-28 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Occupy', '0012_auto_20230627_2137'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Occupation',
        ),
        migrations.RemoveField(
            model_name='clique',
            name='occupation',
        ),
    ]
