# Generated by Django 3.2.13 on 2023-07-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Occupy', '0016_auto_20230718_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clique',
            options={'ordering': ['-created_at'], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AddField(
            model_name='clique',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='groups', to='Occupy.Tag', verbose_name='topics'),
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='posts', to='Occupy.Tag', verbose_name='tags'),
        ),
    ]
