# Generated by Django 3.2.13 on 2023-07-19 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Occupy', '0018_cliquemember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clique',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='TagType',
        ),
    ]
