# Generated by Django 3.2.13 on 2023-07-19 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Occupy', '0020_auto_20230719_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='CliqueMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_type', models.CharField(choices=[('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', help_text='\n            ADMIN: Has (all)permissions to add or remove members as moderators, ban or mute members.<br>\n            MODERATOR: Has permission to add, remove, ban or mute members.<br>\n            MEMBER: Can post, like, comment, share, bookmark group posts.\n        ', max_length=10)),
                ('clique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='Occupy.clique')),
                ('occupier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group Member',
                'verbose_name_plural': 'Group Members',
            },
        ),
        migrations.AlterField(
            model_name='clique',
            name='occupants',
            field=models.ManyToManyField(blank=True, related_name='cliques', to='Occupy.CliqueMember'),
        ),
    ]
