# Generated by Django 3.2.13 on 2023-07-19 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Occupy', '0022_auto_20230719_2109'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clique',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='clique',
            name='occupation',
        ),
    ]
