# Generated by Django 3.2.13 on 2023-07-19 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Occupy', '0023_auto_20230719_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='clique',
            name='occupation',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='clique',
            unique_together={('name', 'occupation')},
        ),
    ]
