# Generated by Django 3.2.13 on 2023-07-20 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Occupy', '0024_auto_20230719_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clique',
            name='occupiers',
        ),
        migrations.AddField(
            model_name='clique',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='clique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Occupy.clique'),
        ),
        migrations.DeleteModel(
            name='CliqueMember',
        ),
    ]
