# Generated by Django 3.2 on 2023-07-20 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Occupy', '0025_auto_20230720_1135'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clique',
            unique_together=set(),
        ),
    ]
