# Generated by Django 3.2 on 2023-07-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Occupy', '0026_alter_clique_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clique',
            options={'ordering': ['-created_at']},
        ),
    ]
