# Generated by Django 3.2 on 2023-07-20 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Occupy', '0027_alter_clique_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clique',
            options={'ordering': ['-created_at'], 'verbose_name': 'Clique', 'verbose_name_plural': 'Cliques'},
        ),
        migrations.AlterUniqueTogether(
            name='clique',
            unique_together={('name', 'occupation')},
        ),
    ]
