# Generated by Django 3.2 on 2023-07-20 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Occupy', '0028_auto_20230720_1437'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clique',
            unique_together=set(),
        ),
    ]
