# Generated by Django 3.2 on 2023-07-20 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Occupy', '0029_alter_clique_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clique',
            unique_together={('name', 'occupation')},
        ),
    ]
