# Generated by Django 3.2 on 2023-07-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Occupy', '0030_alter_clique_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clique',
            options={},
        ),
        migrations.AlterField(
            model_name='clique',
            name='level',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='public', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='clique',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='clique',
            name='description',
        ),
        migrations.RemoveField(
            model_name='clique',
            name='members',
        ),
        migrations.RemoveField(
            model_name='clique',
            name='occupier',
        ),
    ]
