# Generated by Django 3.2 on 2023-07-22 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Occupy', '0031_auto_20230721_0158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clique',
            options={'ordering': ['-created_at'], 'verbose_name': 'Clique', 'verbose_name_plural': 'Cliques'},
        ),
        migrations.AddField(
            model_name='clique',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clique',
            name='occupier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliques', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clique',
            name='level',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', help_text='  \n        Public: Any user can join a public clique\n        Private: Requires an invite to join clique\n        ', max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='clique',
            unique_together={('name', 'occupation')},
        ),
    ]
