# Generated by Django 3.2 on 2023-07-23 19:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Occupy', '0034_remove_clique_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='clique',
            name='members',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='clique',
            unique_together={('name',)},
        ),
    ]
