# Generated by Django 3.2.13 on 2023-09-18 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Occupy', '0038_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
