# Generated by Django 3.2.13 on 2023-09-22 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Occupy', '0039_remove_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
    ]
