# Generated by Django 3.2.13 on 2023-09-22 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Occupy', '0041_alter_comment_occupier'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
