# Generated by Django 5.0.6 on 2024-12-04 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Occupy', '0049_rate_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
