# Generated by Django 5.0.6 on 2024-12-08 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Occupy', '0050_delete_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='clique',
            name='reviews',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clique_reviews', to='Occupy.review'),
        ),
        migrations.AlterField(
            model_name='review',
            name='clique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clique_reviews', to='Occupy.clique'),
        ),
    ]
