# Generated by Django 5.0.6 on 2024-12-09 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Occupy', '0051_clique_reviews_alter_review_clique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clique',
            name='reviews',
        ),
        migrations.AlterField(
            model_name='review',
            name='clique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Occupy.clique'),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(),
        ),
    ]
