# Generated by Django 5.0.6 on 2024-12-15 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Occupy', '0052_remove_clique_reviews_alter_review_clique_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
