# Generated by Django 5.0.6 on 2024-12-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Occupy', '0054_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
