# Generated by Django 5.0.6 on 2024-12-23 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Occupy', '0056_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='clique',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Occupy.clique'),
        ),
    ]
