# Generated by Django 5.0.6 on 2025-01-20 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Occupy', '0049_review'),
        ('Occupy', '0057_alter_review_clique'),
    ]

    operations = [
    ]
