# Generated by Django 5.2.6 on 2025-10-06 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="occupier",
            name="is_business_page",
            field=models.BooleanField(default=False),
        ),
    ]
