# Generated by Django 5.2.6 on 2025-10-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="occupier",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="User's biography or description",
                max_length=500,
                null=True,
            ),
        ),
    ]
