# Generated by Django 5.2.6 on 2025-10-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_occupier_is_business_page"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="occupier",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "Occupier",
                "verbose_name_plural": "Occupiers",
            },
        ),
        migrations.AddField(
            model_name="occupier",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="User's profile image",
                null=True,
                upload_to="profiles/",
            ),
        ),
        migrations.AlterField(
            model_name="occupier",
            name="date_joined",
            field=models.DateField(
                auto_now_add=True,
                help_text="Date when the user registered",
                verbose_name="date joined",
            ),
        ),
        migrations.AlterField(
            model_name="occupier",
            name="email",
            field=models.EmailField(
                help_text="User's email address (used for login)",
                max_length=59,
                unique=True,
                verbose_name="email",
            ),
        ),
        migrations.AlterField(
            model_name="occupier",
            name="first_name",
            field=models.CharField(
                blank=True, help_text="User's first name", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="occupier",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user account should be treated as active",
            ),
        ),
        migrations.AlterField(
            model_name="occupier",
            name="is_admin",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user has admin privileges",
            ),
        ),
        migrations.AlterField(
            model_name="occupier",
            name="is_business_page",
            field=models.BooleanField(
                default=False, help_text="Indicates if this is a business account"
            ),
        ),
        migrations.AlterField(
            model_name="occupier",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into the Django admin site",
            ),
        ),
        migrations.AlterField(
            model_name="occupier",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them",
            ),
        ),
        migrations.AlterField(
            model_name="occupier",
            name="last_login",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Timestamp of last login",
                verbose_name="last login",
            ),
        ),
        migrations.AlterField(
            model_name="occupier",
            name="last_name",
            field=models.CharField(
                blank=True, help_text="User's last name", max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="occupier",
            name="occupations",
            field=models.CharField(
                help_text="User's occupation(s) or profession", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="occupier",
            name="private_account",
            field=models.BooleanField(
                default=False, help_text="Indicates if the account is private"
            ),
        ),
        migrations.AlterField(
            model_name="occupier",
            name="username",
            field=models.CharField(
                help_text="Unique username (used for login)", max_length=30, unique=True
            ),
        ),
    ]
