# Generated by Django 5.2.6 on 2025-10-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_occupier_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occupier",
            name="occupations",
            field=models.CharField(
                blank=True,
                help_text="User's occupation or profession",
                max_length=200,
            ),
        ),
    ]
