# Generated by Django 5.2.6 on 2025-10-07 05:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_occupier_options_occupier_profile_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="occupier",
            name="followers",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who follow this user",
                related_name="occupier_following",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="occupier",
            name="following",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users this user is following",
                related_name="occupier_followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
