# Generated by Django 5.2.6 on 2025-10-07 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="availability",
            name="provider",
            field=models.ForeignKey(
                help_text="User this availability is for",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="client",
            field=models.ForeignKey(
                help_text="User booking the service",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="client_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="provider",
            field=models.ForeignKey(
                help_text="User providing the service",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="provider_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clique",
            name="members",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="clique",
            name="occupier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cliques",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="clique",
            field=models.ForeignKey(
                help_text="Clique the booking belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="core.clique",
            ),
        ),
        migrations.AddField(
            model_name="availability",
            name="clique",
            field=models.ForeignKey(
                help_text="Clique this availability belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availabilities",
                to="core.clique",
            ),
        ),
        migrations.AddField(
            model_name="cliquepost",
            name="clique",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts_set",
                to="core.clique",
            ),
        ),
        migrations.AddField(
            model_name="commentpost",
            name="occupier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="clique",
            name="occupation",
            field=models.ForeignKey(
                blank=True,
                help_text="The occupation category this clique is associated with",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cliques",
                to="core.occupation",
            ),
        ),
        migrations.AddField(
            model_name="occupation",
            name="category",
            field=models.ForeignKey(
                help_text="The category this occupation belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="occupations",
                to="core.occupationcategory",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="clique",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="core.clique",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="occupier",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="like",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="core.post",
            ),
        ),
        migrations.AddField(
            model_name="commentpost",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="core.post",
            ),
        ),
        migrations.AddField(
            model_name="cliquepost",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cliques_set",
                to="core.post",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="booking",
            field=models.OneToOneField(
                help_text="Booking being reviewed",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="core.booking",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="clique",
            field=models.ForeignKey(
                help_text="Clique associated with the review",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="core.clique",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                help_text="User who left the review",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="clique",
            field=models.ForeignKey(
                help_text="Clique offering this service",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="core.clique",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="provider",
            field=models.ForeignKey(
                help_text="User providing this service",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="service",
            field=models.ForeignKey(
                help_text="Service being booked",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="core.service",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="availability",
            unique_together={("provider", "date", "start_time", "end_time")},
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("post", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="cliquepost",
            unique_together={("clique", "post")},
        ),
        migrations.AlterUniqueTogether(
            name="booking",
            unique_together={("service", "date", "start_time")},
        ),
    ]
