# Generated by Django 5.2.6 on 2025-10-06 03:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="availability",
            options={
                "ordering": ["date", "start_time"],
                "verbose_name": "Availability",
                "verbose_name_plural": "Availabilities",
            },
        ),
        migrations.AlterModelOptions(
            name="booking",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
            },
        ),
        migrations.AlterModelOptions(
            name="cliquepost",
            options={
                "verbose_name": "Clique Post",
                "verbose_name_plural": "Clique Posts",
            },
        ),
        migrations.AlterModelOptions(
            name="commentpost",
            options={
                "ordering": ["-date"],
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.AlterModelOptions(
            name="follow",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Follow",
                "verbose_name_plural": "Follows",
            },
        ),
        migrations.AlterModelOptions(
            name="review",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
            },
        ),
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["title"],
                "verbose_name": "Service",
                "verbose_name_plural": "Services",
            },
        ),
        migrations.RenameField(
            model_name="post",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="clique",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="cliques/"),
        ),
        migrations.AddField(
            model_name="clique",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="clique",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("posted", "Posted"),
                    ("archived", "Archived"),
                ],
                default="posted",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="commentpost",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="core.post",
            ),
        ),
    ]
