# Generated by Django 5.2.6 on 2025-10-08 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created.",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated.",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete flag - True if record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft-deleted.",
                        null=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="Message content", max_length=1000),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the message has been read by the recipient",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the message was read",
                        null=True,
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="User who received the message",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        help_text="User who sent the message",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
                "ordering": ["created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created.",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated.",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete flag - True if record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft-deleted.",
                        null=True,
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        help_text="Users participating in this conversation",
                        related_name="conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_message",
                    models.ForeignKey(
                        blank=True,
                        help_text="The most recent message in this conversation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversation_last",
                        to="core.message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conversation",
                "verbose_name_plural": "Conversations",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created.",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated.",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete flag - True if record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft-deleted.",
                        null=True,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("LIKE", "Like"),
                            ("COMMENT", "Comment"),
                            ("FOLLOW", "Follow"),
                            ("BOOKING_REQUEST", "Booking Request"),
                            ("BOOKING_CONFIRMED", "Booking Confirmed"),
                            ("BOOKING_CANCELLED", "Booking Cancelled"),
                            ("REVIEW", "Review"),
                            ("SYSTEM", "System"),
                        ],
                        help_text="Type of notification",
                        max_length=20,
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Notification title", max_length=200),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Notification message content", max_length=500
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the notification has been read",
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the notification was read",
                        null=True,
                    ),
                ),
                (
                    "post_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Related post ID (for likes, comments)",
                        null=True,
                    ),
                ),
                (
                    "comment_id",
                    models.BigIntegerField(
                        blank=True, help_text="Related comment ID", null=True
                    ),
                ),
                (
                    "booking_id",
                    models.BigIntegerField(
                        blank=True, help_text="Related booking ID", null=True
                    ),
                ),
                (
                    "clique_id",
                    models.BigIntegerField(
                        blank=True, help_text="Related clique ID", null=True
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="User who receives the notification",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who triggered the notification (null for system notifications)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
                "ordering": ["-created"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when the record was created.",
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when the record was last updated.",
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="Soft delete flag - True if record is deleted.",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Timestamp when the record was soft-deleted.",
                        null=True,
                    ),
                ),
                (
                    "email_likes",
                    models.BooleanField(
                        default=True, help_text="Receive email notifications for likes"
                    ),
                ),
                (
                    "email_comments",
                    models.BooleanField(
                        default=True,
                        help_text="Receive email notifications for comments",
                    ),
                ),
                (
                    "email_follows",
                    models.BooleanField(
                        default=True,
                        help_text="Receive email notifications for new followers",
                    ),
                ),
                (
                    "email_bookings",
                    models.BooleanField(
                        default=True,
                        help_text="Receive email notifications for booking updates",
                    ),
                ),
                (
                    "email_reviews",
                    models.BooleanField(
                        default=True,
                        help_text="Receive email notifications for reviews",
                    ),
                ),
                (
                    "email_system",
                    models.BooleanField(
                        default=True,
                        help_text="Receive email notifications for system messages",
                    ),
                ),
                (
                    "push_likes",
                    models.BooleanField(
                        default=True, help_text="Receive push notifications for likes"
                    ),
                ),
                (
                    "push_comments",
                    models.BooleanField(
                        default=True,
                        help_text="Receive push notifications for comments",
                    ),
                ),
                (
                    "push_follows",
                    models.BooleanField(
                        default=True,
                        help_text="Receive push notifications for new followers",
                    ),
                ),
                (
                    "push_bookings",
                    models.BooleanField(
                        default=True,
                        help_text="Receive push notifications for booking updates",
                    ),
                ),
                (
                    "push_reviews",
                    models.BooleanField(
                        default=True, help_text="Receive push notifications for reviews"
                    ),
                ),
                (
                    "push_system",
                    models.BooleanField(
                        default=True,
                        help_text="Receive push notifications for system messages",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        help_text="User these settings belong to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Settings",
                "verbose_name_plural": "Notification Settings",
                "abstract": False,
            },
        ),
    ]
