# Generated by Django 5.2.6 on 2025-10-06 06:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_availability_clique_availability_day_of_week_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="body",
        ),
        migrations.AddField(
            model_name="review",
            name="booking",
            field=models.OneToOneField(
                blank=True,
                help_text="The booking this review is for",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review",
                to="core.booking",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="comment",
            field=models.TextField(
                blank=True, help_text="Optional review comment", null=True
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="rating",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "1 star"),
                    (2, "2 stars"),
                    (3, "3 stars"),
                    (4, "4 stars"),
                    (5, "5 stars"),
                ],
                default=5,
                help_text="Rating from 1-5 stars",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="clique",
            field=models.ForeignKey(
                help_text="The clique/business being reviewed",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="core.clique",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                help_text="The user who wrote this review",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews_written",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="core.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Like",
                "verbose_name_plural": "Likes",
                "ordering": ["-created_at"],
                "unique_together": {("post", "user")},
            },
        ),
    ]
